language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      cache: apt
      dist: xenial

notifications:
  irc:
    channels:
      - "chat.freenode.net#portapack"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      # TODO: The "build_number.1" in this URL is almost certainly wrong, but correct value not available from Travis?
      - "Firmware download : https://portapack-h1-builds.s3.amazonaws.com/%{repository_slug}/%{build_number}/%{build_number}.1/build/firmware/portapack-h1-firmware-%{commit}.tar.bz2"

before_install:
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-arm-embedded -y

script:
  # TODO: Introduce top-level Makefile, this is lame.
  - mkdir build/
  - pushd build/
  - cmake ..
  - make release
  - popd

addons:
  apt:
    packages:
      - dfu-util
  artifacts:
    paths:
      - $(ls build/firmware/portapack-h1-havoc-*.tar.bz2 | tr "\n" ":")
      - $(ls build/firmware/portapack-h1-havoc-*.zip | tr "\n" ":")
